### PR TITLE
FIX: Fix examples

### PR DESCRIPTION
**Pull request by larsoner**
After this PR `make pyqt4`, `make nobackend`, `make flake` all pass, and `make examples` has only 8 failures, all of which look like one of these two:

```
----------------------------------------------------------------------
Example basics/scene/volume.py failed (0):
----------------------------------------------------------------------
INFO: Variable u_filter is not an active uniform
INFO: Variable u_id_color is not an active uniform
INFO: Variable u_enabled is not an active uniform

----------------------------------------------------------------------

..............
----------------------------------------------------------------------
Example basics/visuals/mesh.py failed (0):
----------------------------------------------------------------------
INFO: Variable a_v_color is not an active attribute
```

It looks like there is some problem with the `Volume` visual not having the filters attached properly. I'm not sure where the `a_v_color` thing comes from -- @campagnola do you have some idea? Once we have these, I think tests will pass on my system!

### CODE REVIEW

**Comment by bollu** [comment]
@Eric89GXL that's weird - `MeshVisual` is failing? I'll take a look

**Comment by larsoner** [comment]
The unit tests are not failing, it's the examples have that output suggesting that some variable is not being set properly. Examples should not have output like this, it suggests something is mis-configured with the Visual.

**Comment by larsoner** [comment]
Run any example with a mesh and you'll see that `INFO` output, we need to figure out where it's coming from and fix it. Sometimes it says something about `u_v_color` instead, so it probably has to do with color setting, and maybe both variables always get set even though for a given color configuration only one of them should be.

**Comment by bollu** [comment]
ah, okay. I'll fix this :) must be my mess-up when I was porting over `MeshVisual`

**Comment by bollu** [comment]
@Eric89GXL does #19 correct the bug for you?

**Comment by larsoner** [comment]
Yep, and that looks like the right fix to me. Now it's just the `Volume` visual not getting the filters attached properly. @bollu do you have any idea how to fix that? I don't think you transformed the `Volume` visual, but maybe you've been digging through the shaders and system enough to be able to tell.

**Comment by bollu** [comment]
I'll look :)

**Comment by bollu** [comment]
So, I've been trying to track this down. From what I can tell,  It's the picking shader that uses the `id_filter`

```
vispy/vispy/visuals/filters/picking.py

        self.shader = Function("""
            void picking_filter() {
                if( $enabled == 0 )
                    return;
                if( gl_FragColor.a == 0 )
                    discard;
                gl_FragColor = $id_color;
            }
        """)
```

I'm hunting down where filters get applied right now.

**Comment by larsoner** [comment]
@bollu @campagnola `VolumeVisual` fixed. For some reason the filters were being put in the incorrect function, moving the `main` code to the bottom of the shader fixed it (!). Not the best workaround, but it should allow us to get this merged.

Ready for review/merge from my end. This PR in combination with #19 from @bollu gets `flake`, `unit`, and `examples` tests passing on my system, so we might be ready for a `master` merge!

**Comment by bollu** [comment]
Eric, how'd you track that down? That's so crazy. I'd love to learn to
debug stuff like this -_^

Also, awesome! Guess we can finally merge it :)

**Comment by larsoner** [comment]
I `python examples/basics/scene/volumepy --vispy-log=debug,Fragment`. The `debug` sets the logging level to debug, and the `Fragment` is a string to match. This causes (among other things) the code for the fragment shader to be printed before being sent off to the GPU to be compiled. I saw the filter functions were put in the last function in the shader snippet, even though that wasn't the `main` function.

**Comment by bollu** [comment]
`--vispy-log` is slick. Hadn't known that! thanks for sharing :)

**Comment by larsoner** [comment]
Ping @campagnola, any time to look at these last few PRs this week? It would be good to get this merged into `master` ASAP.

**Comment by larsoner** [comment]
This plus #19 make tests pass for me

**Comment by larsoner** [comment]
@campagnola I'm closing this, I think we should do the final few iterations on `vispy/scenegraph-update` so that others are notified. We probably should have switched to that model once we had a huge PR going with PRs into your branch a month or two ago, but it's probably still worth doing now.

**Pull request closed without merging**
