### PR TITLE
Isocurve/Isoline 2nd

### PR DESCRIPTION
**Pull request by kmuehlbauer**
I honestly apologize for the commit-mess created in PR #9.

Adresses vispy#989 (and vispy#974 partially).

The latest status of Isoline/Isocurve I put in a clean checkout of campagnola/scenegraph-update and is represented with this pr. Sorry again for any inconvenience.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Have you run all the related examples and tests to make sure they work?

**Comment by kmuehlbauer** [comment]
* examples/basics/scene/isocurve.py example works and is creating same behaviour as before the addition.
* examples/basics/scene/isocurve_for_trisurface.py works, but is missing one level in the output. I'm trying to figure that out by tomorrow.
* examples/demo/isocurve_for_trisurface_qt.py also works with same behaviour as the basics/scene counterpart

There seem to be only the three related examples mentioned above. There are no dedicated examples for isoline/isocurve in examples/visuals.

For the code, for testing I wrote two examples for use cases, they run actually. I need to clean them up. There might be some other glitches left, which I haven't found yet, but at least the examples are working.

**Comment by Eric89GXL** [comment]
Let me know when the number of levels is fixed, then this should be good

**Comment by kmuehlbauer** [comment]
Found the missing line, the second line was actually written twice in the iso_mesh_line-function. 
Some minor fixes added in data- and color-handling.  
All three examples running fine. Also my not yet ready examples on updating existing isoline/isocurve are working. If I have them ready, where should I put them?

**Comment by Eric89GXL** [comment]
Do they use `scene` or just `app` and `visuals`? If they use `SceneCanvas` they should go in `examples/basics/scene`, otherwise in `examples/basics/visuals`

**Comment by kmuehlbauer** [comment]
At the moment the Isocurve example is using SceneCanvas with Viewbox. The trisurface (Isoline) I find `isocurve_for_trisurface_qt.py` quite nice, because it's easily extendable.

So there would be one under `examples/basics/scene` and the other in `examples/demo/scene`.

Also tested a 'contour'-plotwidget implementation, which runs under `campagnola/demos`-branch, but not with the additions. So my impression is to add this contour-plot if the scenegraph-update and the demos-branch is merged.

**Comment by Eric89GXL** [comment]
Don't bother with `examples/demo/scene`, I've removed that folder in my other PR that got merged. For now maybe just do the one that works (examples/basics/scene one), then. That way this can be merged without depending on any other branches.

**Comment by kmuehlbauer** [comment]
I'm not really sure if this "blinkenlights" showcase suits here, I tried to show as much as possible.

**Comment by Eric89GXL** [comment]
The new example is neat :)

I get a warning when running your example, but it's a warning I've gotten on other examples so I don't think it's your problem:
```
WARNING: Traceback (most recent call last):
  File "examples/basics/scene/isocurve_updates.py", line 36, in <module>
    grid.add_widget(vb1, 0, 0)
  File "/home/larsoner/custombuilds/vispy/vispy/scene/widgets/grid.py", line 106, in add_widget
    widget.parent = self
  File "/home/larsoner/custombuilds/vispy/vispy/scene/node.py", line 183, in parent
    self._set_canvas(parent.canvas)
  File "/home/larsoner/custombuilds/vispy/vispy/scene/node.py", line 307, in _set_canvas
    ch._set_canvas(c)
  File "/home/larsoner/custombuilds/vispy/vispy/scene/node.py", line 307, in _set_canvas
    ch._set_canvas(c)
  File "/home/larsoner/custombuilds/vispy/vispy/scene/node.py", line 309, in _set_canvas
    self.events.canvas_change(old=old, new=c)
  File "/home/larsoner/custombuilds/vispy/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/larsoner/custombuilds/vispy/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/home/larsoner/custombuilds/vispy/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/larsoner/custombuilds/vispy/vispy/scene/cameras/base_camera.py", line 414, in on_canvas_change
    event.old.events.key_press.disconnect(self.viewbox_key_event)
```
@campagnola have you seen this before? It comes up on a couple of other examples.

**Comment by kmuehlbauer** [comment]
JFTR: I get that warning also. 

OK, then I'll wait until merged.

There are more ideas on howto improve the isocurve for using as contour plots (much like matplotlib, with text and applying levels while zooming etc) but it is possibly better to leave that for now.

**Comment by Eric89GXL** [comment]
Yeah please wait until this is all in `vispy/master`, I think getting this big branch merged should be the priority for now.

**Comment by kmuehlbauer** [comment]
Sure, I fully agree!

**Comment by campagnola** [comment]
Looks good! Sorry for the delay; it has been a crazy week.
Thanks!

**Pull request merged**
